### ISSUE TITLE
ld: library not found for -lgcc_s.10.4

### ISSUE THREAD

**Issue by najidebian** [mulle-kybernetik/homebrew-software#2]
I am on Mac OS Mojave10.14 and I am having this error when running 
brew install mulle-kybernetik/software/mulle-xcode-settings

ld: library not found for -lgcc_s.10.4
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** INSTALL FAILED **
I tried this as suggested by many after a google search but with no success
cd /usr/local/lib && sudo ln -s ../../lib/libSystem.B.dylib libgcc_s.10.4.dylib

**Comment by mulle-nat** [comment]
I didn't even know that there is a dependency to `gcc_s` there, let alone: I don't even know what `gcc_s` is :-) I don't have Mojave on this machine here, it will have to wait a few days...

**Comment by najidebian** [comment]
Thanks Nat for your time and concern :) I will be waiting.

**Comment by mulle-nat** [comment]
I have this feeling, this is because the baseline for mulle-xcode-settings is 10.4 and Apple removed the libgcc_s.10.4 library, but their toolchain still emits a link request for it.

**Comment by mulle-nat** [comment]
Baseline is now 10.6 and it seems to work.

**Comment by najidebian** [comment]
Yes it is now working. Thanks Nat for following up and for ur time. Have a great day
